### PR TITLE
Resurrect glyphs involving firearms

### PR DESCRIPTION
**Pull request by Crissov**
U+1F93B Modern Penthatlon
U+1F946 Rifle

These two were added to Unicode 9.0, but their `Emoji` property was
revoked in the last minute upon request by Apple and Google in a
misguided attempt to discourage guns.

### CODE REVIEW

**Comment by Crissov** [comment]
master branch
master branch

**Comment by eosrei** [comment]
I'd leave these out to avoid politicizing this project. They are not part of the emoji spec.

**Comment by Crissov** [comment]
As I see it, Emojitwo just provides the artwork and it's very okay to offer options. Other projects can choose to omit some of it. The version of your [emojione-color-font](https://github.com/eosrei/emojione-color-font) that I'm using, however, does support them, too. &#x1f93b;&#x1f946;

As a collaborative open source project, we can and should be more open than what major vendors agree upon (which is what is documented in UTS#51). Also see the [readme](https://github.com/EmojiTwo/emojitwo/blob/master/README.md#plans), [contributing doc](https://github.com/EmojiTwo/emojitwo/blob/master/CONTRIBUTING.md#emoji-artwork) and, most 
importantly, #62.

**Comment by eosrei** [comment]
I accept the graphics on technical and "offering options" grounds. ;) I still disagree about their inclusion since they were specifically removed from Unicode and your original statement on this PR includes only subjective reasons. IMO It'll be easier long term to simply follow the spec in this case.

> The version of your emojione-color-font that I'm using, however, does support them, too. 

You are using v1.2 of emojione-color-font. The inclusion in v1.2 is no political statement, I was following upstream. I removed these characters in v1.3 to match EmojiOne: https://github.com/eosrei/emojione-color-font/commit/39230a621a2253c722c2c146d3c4d4a67bce508d  I'm willing to delete that release to make it clear. Please do not say I am a hypocrite.

**Comment by Crissov** [comment]
I'm not saying you're a hypocrite. I was just surprised because I didn't remember you removed them later on.

I added them because that took very little effort or skill, not because I liked guns (which I don't). 

UTS#51 is often taken as prescriptive when it's really meant to be descriptive, but let's discuss that in #62.

**Pull request merged**
