### PR TITLE
UK flags

### LINKED ISSUE #57: England
U+1F3F4+E0067+E0062+E0065+E006E+E0067+E007F
master branch [emoji5 branch](https://github.com/EmojiTwo/emojitwo/blob/emoji5/svg/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.svg)

English Flag, St. George Saltire, `GB-ENG`

http://emojipedia.org/flag-for-england/
http://unicode.org/emoji/charts/emoji-released.html#1f3f4_e0067_e0062_e0065_e006e_e0067_e007f

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
New design for Scotland flag that is closer to the original – serves also as base for redone N. Ireland and Jersey flags.

Adds flag for Wales.

All done with Inkscape, so no longer minified.

Existing England flag is OK.

Fixes #57 #58 #59 (NIR has no bug number)

### CODE REVIEW

**Comment by Crissov** [comment]
Hmm, I tend to agree that these are better. I based the English flag either upon Georgia's or Guernsey's &ndash; don't quite remember &ndash; and the Scottish flag on Jersey's:

GE GG  JE

I'm not sure we should choose the red saltire for Northern Ireland. https://github.com/Crissov/unicode-proposals/issues/358

**Comment by KAMiKAZOW** [comment]
Well, the Ulster flag was abolished and according to Wikipedia it is seen as especially politically charged. The St Patrick's Cross seems to be the most neutral nowadays (after the Union Jack, of course). It is also being used by institutions like the police: https://en.wikipedia.org/wiki/Police_Service_of_Northern_Ireland

The most prominent use of the Ulster flag is football and IMO the police and other formal institutions trump football.

Not sure about Google's reasoning for their inclusion of the Ulster flag. Maybe for historic reasons. For what I care we could even leave it out. I probably would not even have created one if it weren't a simple color swap of the Scottish flag.

**Comment by Crissov** [comment]
Noto uses https://github.com/behdad/region-flags but not unconditionally and we shall see what Google, Apple and Twitter will actually release after June.

Anyway, if we use your variants of the Scottish and Northern Irish flags, we should also change Jersey at least.

**Comment by KAMiKAZOW** [comment]
Redid everything from scratch. The inclination of the Andrew/Patrick crosses now match that of Jamaica's flag. Also did the Jersey flag while I was at it.

**Comment by Crissov** [comment]
Android O Preview does not include a Northern Ireland flag emoji and neither does Twitter Twemoji 2.3.

**Comment by KAMiKAZOW** [comment]
Should we delete it then? Or just don't care and keep the current one for now?

**Comment by Crissov** [comment]
I think we should keep it. If local user demand becomes clearer, we can still change later on, even after the Flags branch has been merged into Master.

**Pull request merged**
