### PR TITLE
better shark emoji

### PR DESCRIPTION
**Pull request by blackle**
sharks are friends, not fiends

I've always hated the emojione shark. The forced perspective looks terrible, and there is more to a shark than just their teeth. This would also bring it more in line with apple, google, twitter, and facebook's emoji.

accept/reject this at your own discretion

### CODE REVIEW

**Comment by Crissov** [comment]
Thank you very much for your contribution! I like how you are perfectly matching the existing style.

I tend to agree that a documentary example picture of a shark should not show it as a mean beast lusting for blood, but I'm not as sure whether a graphic without visible teeth would be appropriate for emoji use.  Most [other vendors](http://emojipedia.org/shark/) show a slightly opened mouth &ndash; note Google's upcoming change. Let me also quote the relevant part of my comment in #88:

> - Facebook’s original [Shark 🦈](http://emojipedia.org/shark/) emoticon `(^^^)` just represented mouth and teeth (→ _Jaws_) and thus their picture was just showing a shark’s wide-open mouth. I’d like to have that and the classic dorsal fin in waves `~~~/\\~~~` as well. A font could automatically trigger the latter in a sequence like 🦈&zwj;🏊 or 🦈&zwj;🏄 (or 🏊&zwj;🦈 or 🏄&zwj;🦈) … `____/\___\o/___`.

That being said, @blackle's image certainly is an improvement over the existing one. 

Shark proposed new Shark Dolphin old Dolphin

The Shark emoji must also be easy to discern from the [Dolphin](http://emojipedia.org/dolphin/). I have already removed the waves from the Emojione 2.2 graphic in the Emojitwo SVG, but the PNG has not been updated in the repository yet.

**Comment by blackle** [comment]
By a strange coincidence, Emojione 3.1 was just released that includes a new shark emoji https://www.emojione.com/emoji/1f988

I agree some teeth is probably necessary. I'll put some in tonight

**Comment by blackle** [comment]
Nevermind, did it just now, lol

**Comment by Crissov** [comment]
Great! Maybe it's just me, but doesn't its tail look a bit too much like a fluke?

**Comment by blackle** [comment]
How do you mean?

**Comment by blackle** [comment]
oh, I see it, the asymmetry of the tail looks more like perspective. so it looks more like it's flat and symmetrical like a whale's tail

ok I think I know how to fix that. I'm at work now so I'll probably fix that later tonight

**Comment by blackle** [comment]
how's this?

**Comment by Crissov** [comment]
I'm afraid to sound overly critic, but is that dent in its tail intentional? If it is, this is fine for me and I will merge it as soon as possible, unless @KAMiKAZOW or someone else disagrees.

**Comment by blackle** [comment]
It is intentional, I based it on this: http://www.sharktrust.org/shared/juniors/basking_tail_web.jpg
shark tails are asymmetrical from the top vs the bottom and I wanted to make that clear

**Comment by KAMiKAZOW** [comment]
It's all good. Thanks.

**Pull request merged**
